### ISSUE TITLE
sage-notebook-0.11.4-r4 fails to install with "PYTHON needs to be set for PYTHON_SITEDIR to be exported, or requested before it"

### ISSUE THREAD

**Issue by veelai** [cschwan/sage-on-gentoo#384]
Hi,

I get the following error on ~amd64.

<pre>
running install_scripts
 * python2_7: running distutils-r1_run_phase distutils-r1_python_install_all
 * ERROR: sci-mathematics/sage-notebook-0.11.4-r4::sage-on-gentoo failed (install phase):
 *   PYTHON needs to be set for PYTHON_SITEDIR to be exported, or requested before it
 * 
 * Call stack:
 *     ebuild.sh, line  133:  Called src_install
 *   environment, line 3973:  Called python_get_sitedir
 *   environment, line 3661:  Called python_export 'PYTHON_SITEDIR'
 *   environment, line 3247:  Called die
 * The specific snippet of code:
 *                   [[ -n ${PYTHON} ]] || die "PYTHON needs to be set for ${var} to be exported, or requested before it";
</pre>

**Comment by kiwifb** [comment]
That's new. Probably an eclass update that made things "stricter" (`PYTHON` is defined in `pkg_setup`) I'll have a look when I get in the office (in two hours).

**Comment by strogdon** [comment]
The same error here in Prefix. I haven't built the notebook for some time so this could have been just waiting to happen.

**Comment by kiwifb** [comment]
Fairly easy fix once I looked at the ebuild properly. sync and retry, it should work now. Re-open if it doesn't for you.

**Comment by strogdon** [comment]
After a sync I still see the issue. On gentoo as well. 
```
running install_scripts
 * python2_7: running distutils-r1_run_phase python_install_all
>>> Completed installing sage-notebook-0.11.4-r4 into /var/tmp/portage/sci-mathematics/sage-notebook-0.11.4-r4/image/

ecompressdir: bzip2 -9 /usr/share/doc

>>> Installing (1 of 1) sci-mathematics/sage-notebook-0.11.4-r4::sage-on-gentoo
 * ERROR: sci-mathematics/sage-notebook-0.11.4-r4::sage-on-gentoo failed (preinst phase):
 *   PYTHON needs to be set for PYTHON_SITEDIR to be exported, or requested before it
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called pkg_preinst
 *   environment, line 3020:  Called python_get_sitedir
 *   environment, line 3723:  Called python_export 'PYTHON_SITEDIR'
 *   environment, line 3300:  Called die
 * The specific snippet of code:
 *                   [[ -n ${PYTHON} ]] || die "PYTHON needs to be set for ${var} to be exported, or requested before it";
```
So `python_install_all` is run but neither `PYTHON` nor `PYTHON_SITEDIR` are set in `temp/environment`

**Comment by veelai** [comment]
I too see this, but the error message is now a bit different. However I do not see a button to reopen the issue.

<pre>
running install_scripts
 * python2_7: running distutils-r1_run_phase python_install_all
>>> Completed installing sage-notebook-0.11.4-r4 into /var/tmp/portage/sci-mathematics/sage-notebook-0.11.4-r4/image/

ecompressdir: bzip2 -9 /usr/share/doc
 * checking 775 files for package collisions
>>> Merging sci-mathematics/sage-notebook-0.11.4-r4 to /
 * ERROR: sci-mathematics/sage-notebook-0.11.4-r4::sage-on-gentoo failed (preinst phase):
 *   PYTHON needs to be set for PYTHON_SITEDIR to be exported, or requested before it
 * 
 * Call stack:
 *     ebuild.sh, line  133:  Called pkg_preinst
 *   environment, line 3006:  Called python_get_sitedir
 *   environment, line 3709:  Called python_export 'PYTHON_SITEDIR'
 *   environment, line 3286:  Called die
 * The specific snippet of code:
 *                   [[ -n ${PYTHON} ]] || die "PYTHON needs to be set for ${var} to be exported, or requested before it";
</pre>

**Comment by kiwifb** [comment]
Now re-opened `ebuild ... install` worked fine it is after during the merge phase that there is a problem. Stay tuned once I have 5mn to dig it.

**Comment by strogdon** [comment]
Perhaps now
```
--- a/sci-mathematics/sage-notebook/sage-notebook-0.11.4-r4.ebuild
+++ b/sci-mathematics/sage-notebook/sage-notebook-0.11.4-r4.ebuild
@@ -41,7 +41,7 @@ RDEPEND="${CDEPEND}
        java? ( >=sci-chemistry/sage-jmol-bin-14.2.11 )"
 
 pkg_setup() {
-       python_export python2_7 EPYTHON
+       python_export python2_7 PYTHON EPYTHON
 
        # create user to run the server
        if use server ; then
```
I'm not sure why, but the `preinst` phase will pass.

**Comment by kiwifb** [comment]
I believe you are right I will add a few things to the export statement.

**Comment by kiwifb** [comment]
Let's try again now.

**Comment by veelai** [comment]
Works. :)
