### ISSUE TITLE
sage-doc-9.8 won't build

### ISSUE THREAD

**Issue by hackitforfun** [cschwan/sage-on-gentoo#732]
Here's the relevant log file.
[build.log](https://github.com/cschwan/sage-on-gentoo/files/10736097/build.log)

**Comment by kiwifb** [comment]
Thanks for the report. By the look of it, some dependencies are not installed yet when sage-doc is built. This is a geniune dependency issue and I thank you for reporting it.

**Comment by kiwifb** [comment]
Should be fixed by b580cb2ab520f0258e936588d6f276ba6c549fa1 please report if successful.

**Comment by hackitforfun** [comment]
Thank you for the fast response. I just checked by rerun `emerge -va sage`, with several changes including a downgrade to sage-9.7-r5, the sage-doc package still won't build successfully. Here is the new log file.
[build.log](https://github.com/cschwan/sage-on-gentoo/files/10742154/build.log)

**Comment by kiwifb** [comment]
Do you have `sage-data-conway_polynomials` installed? I fixed the dependencies in 9.8 but not in 9.7.

**Comment by hackitforfun** [comment]
Yes, I do have sci-mathematics/sage-data-conway_polynomials-0.5 installed. It is curious that portage wants to do a sage downgrade from 9.8 to 9.7-r5, as the former was successfully built on my machine (~amd64) yesterday.

**Comment by kiwifb** [comment]
Could you also post the result of `equery f sage-data-conway_polynomials` it should have at least build with 9.7. There is something not quite right to figure out there.

**Comment by kiwifb** [comment]
The issues preventing 9.8 to be installed should be fixed by the latest commit in the repo. But I still want to get deeper on the conway_polynomial issue. There is a problem there that need to be looked at deeper.

**Comment by hackitforfun** [comment]
The following two lines are indeed the whole output of `equery f sage-data-conway_polynomials` , which I guess should not be the case.
```
 * Searching for sage-data-conway_polynomials ...
 * Contents of sci-mathematics/sage-data-conway_polynomials-0.5:
```

**Comment by kiwifb** [comment]
What happens when you install it? Logs from `emerge -1v sage-data-conway_polynomials` please.

**Comment by hackitforfun** [comment]
This is the full output of emerge, which indeed seems to be the problem as you suspected.
```
These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 8.10 s.

[ebuild   R    ] sci-mathematics/sage-data-conway_polynomials-0.5::sage-on-gentoo  0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB


>>> Verifying ebuild manifests

>>> Emerging (1 of 1) sci-mathematics/sage-data-conway_polynomials-0.5::sage-on-gentoo
 * conway_polynomials-0.5.tar.bz2 BLAKE2B SHA512 size ;-) ...                                                               [ ok ]
 * Checking whether python3_11 is suitable ...
 *   >=dev-lang/python-3.11.1-r1:3.11 ...                                                                                   [ ok ]
 * Using python3.11 to build (via PYTHON_COMPAT iteration)
>>> Unpacking source...
>>> Unpacking conway_polynomials-0.5.tar.bz2 to /var/tmp/portage/sci-mathematics/sage-data-conway_polynomials-0.5/work
>>> Source unpacked in /var/tmp/portage/sci-mathematics/sage-data-conway_polynomials-0.5/work
>>> Preparing source in /var/tmp/portage/sci-mathematics/sage-data-conway_polynomials-0.5/work ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-mathematics/sage-data-conway_polynomials-0.5/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-mathematics/sage-data-conway_polynomials-0.5/work ...
>>> Source compiled.
>>> Test phase [not enabled]: sci-mathematics/sage-data-conway_polynomials-0.5

>>> Install sci-mathematics/sage-data-conway_polynomials-0.5 into /var/tmp/portage/sci-mathematics/sage-data-conway_polynomials-0.5/image
Traceback (most recent call last):
  File "/var/tmp/portage/sci-mathematics/sage-data-conway_polynomials-0.5/work/spkg-install", line 3, in <module>
    from six.moves import cPickle as pickle
ModuleNotFoundError: No module named 'six'
>>> Completed installing sci-mathematics/sage-data-conway_polynomials-0.5 into /var/tmp/portage/sci-mathematics/sage-data-conway_polynomials-0.5/image

 * Final size of build directory: 1036 KiB (1.0 MiB)
 * Final size of installed tree:     0 KiB


>>> Installing (1 of 1) sci-mathematics/sage-data-conway_polynomials-0.5::sage-on-gentoo
 * checking 0 files for package collisions
>>> Merging sci-mathematics/sage-data-conway_polynomials-0.5 to /
>>> Safely unmerging already-installed instance...
No package files given... Grabbing a set.
>>> Original instance of package unmerged safely.
>>> sci-mathematics/sage-data-conway_polynomials-0.5 merged.

 * GNU info directory index is up-to-date.
```

**Comment by kiwifb** [comment]
Right, there's our culprit. I will fix it ASAP.

**Comment by kiwifb** [comment]
OK, 7b294f1c24236306c294359c912c656295f47e7b is fixing the installation of `sage-data-conway_polynomials`  and make it die on failure rather than just going on its merry way if there is a problem. I will have to inspect other packages to see if other issues like that could pop up.

In any case, after `sage-data-conway_polynomials` is properly installed, `sage-doc` should install as well. Please let me know how it goes.

**Comment by hackitforfun** [comment]
Thanks for the fix and the effort. However, `sage-doc` still won't install after reinstalling successfully the new `sage-data-conway_polynomials`. Here's the output for `equery f sage-data-conway_polynomials`
```
/usr
/usr/share
/usr/share/sage
/usr/share/sage/conway_polynomials
/usr/share/sage/conway_polynomials/conway_polynomials.p
```
The new build log for `sage-doc` is also attached.
[build.log](https://github.com/cschwan/sage-on-gentoo/files/10765273/build.log)

**Comment by kiwifb** [comment]
OK. Two things:
*  what is your version of sphinx
* `equery f sage_docbuild`
please.

**Comment by hackitforfun** [comment]
I have `dev-python/sphinx-6.1.3`.
Below is the output of `equery f sage_docbuild`.

```
/usr
/usr/lib
/usr/lib/python3.10
/usr/lib/python3.10/site-packages
/usr/lib/python3.10/site-packages/sage_docbuild
/usr/lib/python3.10/site-packages/sage_docbuild-9.8.dist-info
/usr/lib/python3.10/site-packages/sage_docbuild-9.8.dist-info/METADATA
/usr/lib/python3.10/site-packages/sage_docbuild-9.8.dist-info/RECORD
/usr/lib/python3.10/site-packages/sage_docbuild-9.8.dist-info/WHEEL
/usr/lib/python3.10/site-packages/sage_docbuild-9.8.dist-info/top_level.txt
/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py
/usr/lib/python3.10/site-packages/sage_docbuild/__main__.py
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/__init__.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/__init__.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/__init__.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/__main__.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/__main__.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/__main__.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/build_options.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/build_options.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/build_options.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/builders.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/builders.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/builders.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/conf.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/conf.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/conf.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/sphinxbuild.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/sphinxbuild.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/sphinxbuild.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/utils.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/utils.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/__pycache__/utils.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/build_options.py
/usr/lib/python3.10/site-packages/sage_docbuild/builders.py
/usr/lib/python3.10/site-packages/sage_docbuild/conf.py
/usr/lib/python3.10/site-packages/sage_docbuild/ext
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__init__.py
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/__init__.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/__init__.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/__init__.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/inventory_builder.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/inventory_builder.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/inventory_builder.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/multidocs.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/multidocs.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/multidocs.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/sage_autodoc.cpython-310.opt-1.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/sage_autodoc.cpython-310.opt-2.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/__pycache__/sage_autodoc.cpython-310.pyc
/usr/lib/python3.10/site-packages/sage_docbuild/ext/inventory_builder.py
/usr/lib/python3.10/site-packages/sage_docbuild/ext/multidocs.py
/usr/lib/python3.10/site-packages/sage_docbuild/ext/sage_autodoc.py
/usr/lib/python3.10/site-packages/sage_docbuild/sphinxbuild.py
/usr/lib/python3.10/site-packages/sage_docbuild/utils.py
/usr/share
/usr/share/doc
/usr/share/doc/sage_docbuild-9.8
/usr/share/doc/sage_docbuild-9.8/README.rst.bz2
```

**Comment by kiwifb** [comment]
`sphinx` is currently moving way too fast. I think the issue here is sphinx 6.1.3. I will impose sphinx-5 as a dependency for now. Can you mask `>=dev-python/sphinx-6.0.0' downgrade sphinx and see if it fixes it?

**Comment by hackitforfun** [comment]
I have successfully merged `sage-doc` using `sphinx-5.3.0`. Thank you very much.

**Comment by kiwifb** [comment]
Added `<dev-python/sphinx-6.0.0` in sage, sage_docbuild and sage-doc's dependencies.
